version: '3.1'

services:
  mini_back-service:
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=mini_back-postgres
    build: ./
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - mini_back
    depends_on:
      - mini_back-postgres
    restart: always

  mini_back-postgres:
    image: postgres
    env_file:
      - ./.env
    restart: always
    networks:
      - mini_back

networks:
  mini_back:
